### ISSUE TITLE
Encryption/Decryption Sync for Mobile and WEB

### ISSUE THREAD

**Issue by GGLozanov** [katapultman/TUESPairs#16]
### Bug Report
Bug Name: Chat crashes upon navigation to it due to unencrypted messages in DB.
Area Path: Login view > Match view > Chat view
Severity: HIGH
Priority: HIGH
Assigned to: @katapultman @marianbitsov23 @martinsimov10a19 
Reported By: @katapultman 
Reported On: 20.04.2020
Reason: Defect
Environment: Xiaomi Redmi 7.

### Description
Chat crashes w/ exception upon decryption attempt of unencrypted messages due to polluted DB and unimplemented encryption from WEB.

### Steps To Reproduce:
1) Login into the Application with a user w/ chat capability (matched with another user)
2) Navigate to the Match view
3) Navigate to Chat view
4) View message history and attempt to send message

### Expected Result
Message history should appear. Upon sent message, it should be added to the history and live communication should be established.

**Comment by marianbitsov23** [comment]
Засега този feature, няма да го има. Поради различния начин на криптиране на двете библиотеки, които Mobile и Web приложението ползват, криптирането на абсолютно еднакви съобщения по един и същ начин е невъзможно. Поради простата причина че ключа и Iv - Intialization vector, са различни за двете библиотеки. В бъдеще този проблем ще бъде оправен и съобщенията ще се криптират. Най-вероятно ще се криптират по друг начин, а не с Advanced Encryption Standard, ами с нещо друго.

**Comment by msimov02** [comment]
There won't be Encryption/Decryption for now because I can't find an Encryption/Decryption algorithm that has the same implementation both for Dart and JavaScript.

**Comment by GGLozanov** [comment]
Fine. Issue closed.
