### ISSUE TITLE
External Sign In Authentication for WEB

### ISSUE THREAD

**Issue by marianbitsov23** [katapultman/TUESPairs#18]
### Bug Report 
Bug Name: Sign In with External Authentication services is not working
Area Path: Login view > User_info view > Home view
Severity: HIGH
Priority: HIGH
Assigned to: @marianbitsov23  @katapultman  @martinsimov10a19 
Reported By: @marianbitsov23 
Reason: Defect
Environment: Microsoft Edge/localhost

### Description 
When a user signs in for the first time with an external platform(Google, Github, Facebook), the firebase AuthProvider + AuthListener automatically handle the authentication in real time, so when this user signs in is for the first time the AuthListener handles the authentication of the user and tries too get his info from the Cloud Firestore (username, isTeacher, GPA, etc.), but since this is a new user he doesn't have any information stored in the Database. And when he gets into the user_info page and navigates to the Home page or the Personal Profile page, the authProvider cannot retrieve the user's data because he authenticated before entering his information, which leads to Exception and the application crashes.

### Steps to reproduce
1) Sign in with one of the external platforms (Google, Github, Facebook)
2) Wait to get redirected to the User_info page, where you can enter your info (username, GPA, etc.)
3) Navigate to either Home page or Personal Profile page

### Expected result (Needed Debug Mode : ON)
The page should throw an exception containing Cannot read property 'includes' from null.
The exception is thrown in the check for the currentUser skipped users, in the render method.

**Comment by marianbitsov23** [comment]
### Update / Fixed
The bug was fixed with chaining asynchronous functions after the External Sign In that get a snapshot from the Cloud Firestore, checks if the snapshot exists and if the snapshot doesn't exist, a new document is created with empty user info. In that way the authentication waits for all this functionality to be completed before proceeding further and authenticating the user and giving it throughout  the whole application provider

**Comment by GGLozanov** [comment]
I'd believed the origin of the bug to lie within a mishap with the asynchronous calls. Good on fixing it otherwise; most impressive.
